### ISSUE TITLE
Keyframe name is broken using version 4.0.0 alpha8 of material ui

### ISSUE THREAD

**Issue by jmdsg** [cssinjs/jss-keyframes#1]
The name generated by the `keyframes` function is broken, it is currently returning `animation-1` for the first keyframe while the actual name in the style sheet is `keyframes-animation-1-0-3-1`.

That's running on development, haven't tried running on production.

And the case is too simple, I don't think a MCVE is needed.

**Comment by HenriBeck** [comment]
This library isn't being used/needed anymore. Scoped keyframes were implemented directly in `jss`

**Comment by HenriBeck** [comment]
For docs on how to use them, check out https://cssinjs.org/jss-syntax?v=v10.0.0-alpha.16#keyframes-animation
